spring:
  datasource:
    url: jdbc:sqlite:sample_pet.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
hibernate:
  show_sql: true
logging:
  level:
    com.twister: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
